package com.vvp.web;
// Generated 16 Apr, 2021 1:32:14 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String password;
     private String email;
     private String role;
     private int detailId;

    public User() {
    }

	
    public User(String role, int detailId) {
        this.role = role;
        this.detailId = detailId;
    }
    public User(String username, String password, String email, String role, int detailId) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.role = role;
       this.detailId = detailId;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public int getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(int detailId) {
        this.detailId = detailId;
    }




}


